### ISSUE TITLE
Difference with json-rte-serializer package?

### ISSUE THREAD

**Issue by alexandereneroth** [contentstack/contentstack-utils-javascript#82]
Hi,
What is the difference between this package and this one: https://github.com/contentstack/json-rte-serializer?

**Comment by sunil-lakshman** [comment]
@alexandereneroth Firstly both are SDKs used to convert JSON content to HTML to render on the frontend. Json RTE serializer additionally provides a way to convert HTML to JSON as well helping in migration from HTML to JSON RTE.
